version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always

  kafka:
    image: wurstmeister/kafka
    depends_on:
     - zookeeper
    restart: always
    ports:
     - "9094:9094"
    environment:
      HOSTNAME_COMMAND: "hostname -i"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    container_name: mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - mosquittodata:/data
volumes:
  mosquittodata:
    
